import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

export interface GameConfig {
  id: string
  title: string
  description: string
  thumbnail: string
  tags: string[]
  component: LazyExoticComponent<ComponentType>
}

export const GAMES: GameConfig[] = [
  {
    id: 'snake',
    title: 'Snake',
    description: 'Classic snake game — eat apples, grow longer, avoid walls.',
    thumbnail: '/thumbnails/snake.png',
    tags: ['classic', '2d'],
    component: lazy(() => import('../games/snake')),
  },
  {
    id: 'game-of-life',
    title: 'Game of Life',
    description: 'Watch cells grow and change. Click to draw your own patterns.',
    thumbnail: '/thumbnails/game-of-life.png',
    tags: ['puzzle', 'simulation'],
    component: lazy(() => import('../games/game-of-life')),
  },
  {
    id: 'banana-chaos',
    title: 'Banana Chaos',
    description: 'You are a banana. Dodge falling peels. Do not slip.',
    thumbnail: '/thumbnails/banana-chaos.png',
    tags: ['silly', 'arcade'],
    component: lazy(() => import('../games/banana-chaos')),
  },
  {
    id: 'bomb-simulator',
    title: 'Bomb Simulator',
    description: 'Buy bombs. Wreck Earth in the arena. Stop repair crews before they fix everything.',
    thumbnail: '/thumbnails/bomb-simulator.png',
    tags: ['arcade', 'simulation'],
    component: lazy(() => import('../games/bomb-simulator')),
  },
  {
    id: 'team-war',
    title: 'Team War',
    description: 'Fight as a blue soldier in a 3D battlefield — WASD, mouse look, click to shoot.',
    thumbnail: '/thumbnails/team-war.png',
    tags: ['3d', 'action'],
    component: lazy(() => import('../games/team-war')),
  },
  {
    id: 'definitely-no-game',
    title: 'Definitely No Game',
    description: 'There is no game here. Please go away. (There might be a game.)',
    thumbnail: '/thumbnails/definitely-no-game.png',
    tags: ['puzzle', 'silly'],
    component: lazy(() => import('../games/definitely-no-game')),
  },
  {
    id: 'bean-blast',
    title: 'Bean Blast',
    description: 'Idle fart clicker — fill your gas tank, blast FP, buy upgrades.',
    thumbnail: '/thumbnails/bean-blast.png',
    tags: ['idle', 'silly'],
    component: lazy(() => import('../games/bean-blast')),
  },
  {
    id: 'brotato',
    title: 'Brotato',
    description: 'Survive waves of enemies and grow stronger.',
    thumbnail: '/thumbnails/brotato.png',
    tags: ['arcade', 'action'],
    component: lazy(() => import('../games/brotato')),
  },
  {
    id: 'cakto',
    title: 'Cakto',
    description: 'Browser game from Apple Bobs.',
    thumbnail: '/thumbnails/cakto.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/cakto')),
  },
  {
    id: 'click-50',
    title: 'Click 50',
    description: 'Click your way to fifty.',
    thumbnail: '/thumbnails/click-50.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/click-50')),
  },
  {
    id: 'clicktopia',
    title: 'Clicktopia',
    description: 'Build your clicking empire.',
    thumbnail: '/thumbnails/clicktopia.png',
    tags: ['idle'],
    component: lazy(() => import('../games/clicktopia')),
  },
  {
    id: 'clippey',
    title: 'Clippey',
    description: 'Clip and play.',
    thumbnail: '/thumbnails/clippey.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/clippey')),
  },
  {
    id: 'dear-diary',
    title: 'Dear Diary',
    description: 'Interactive diary experience.',
    thumbnail: '/thumbnails/dear-diary.png',
    tags: ['story'],
    component: lazy(() => import('../games/dear-diary')),
  },
  {
    id: 'double-pendulum',
    title: 'Double Pendulum',
    description: 'Chaotic double pendulum simulation.',
    thumbnail: '/thumbnails/double-pendulum.png',
    tags: ['simulation'],
    component: lazy(() => import('../games/double-pendulum')),
  },
  {
    id: 'fire-feild',
    title: 'Fire Feild',
    description: 'Fire field action game.',
    thumbnail: '/thumbnails/fire-feild.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/fire-feild')),
  },
  {
    id: 'four',
    title: 'Four',
    description: 'Four-in-a-row puzzle.',
    thumbnail: '/thumbnails/four.png',
    tags: ['puzzle'],
    component: lazy(() => import('../games/four')),
  },
  {
    id: 'frame-flipper',
    title: 'Frame Flipper',
    description: 'Flip frames and match patterns.',
    thumbnail: '/thumbnails/frame-flipper.png',
    tags: ['puzzle'],
    component: lazy(() => import('../games/frame-flipper')),
  },
  {
    id: 'gamble-count',
    title: 'Gamble Count',
    description: 'Gambling math challenge.',
    thumbnail: '/thumbnails/gamble-count.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/gamble-count')),
  },
  {
    id: 'hammer-hammer',
    title: 'Hammer Hammer',
    description: 'Resource gatherer — hammer, upgrade, repeat.',
    thumbnail: '/thumbnails/hammer-hammer.png',
    tags: ['idle'],
    component: lazy(() => import('../games/hammer-hammer')),
  },
  {
    id: 'infiniteair',
    title: 'Infiniteair',
    description: 'Endless air adventure.',
    thumbnail: '/thumbnails/infiniteair.png',
    tags: ['arcade'],
    component: lazy(() => import('../games/infiniteair')),
  },
  {
    id: 'mandelbrot-explore',
    title: 'Mandelbrot Explore',
    description: 'Zoom and explore the Mandelbrot set.',
    thumbnail: '/thumbnails/mandelbrot-explore.png',
    tags: ['simulation'],
    component: lazy(() => import('../games/mandelbrot-explore')),
  },
  {
    id: 'math-drill',
    title: 'Math Drill',
    description: 'Practice math under pressure.',
    thumbnail: '/thumbnails/math-drill.png',
    tags: ['education'],
    component: lazy(() => import('../games/math-drill')),
  },
  {
    id: 'number-listener',
    title: 'Number Listener',
    description: 'Listen and match numbers.',
    thumbnail: '/thumbnails/number-listener.png',
    tags: ['education'],
    component: lazy(() => import('../games/number-listener')),
  },
  {
    id: 'perfect-mine',
    title: 'Perfect Mine',
    description: 'Dig deep, upgrade pickaxes, fight the Miner King.',
    thumbnail: '/thumbnails/perfect-mine.png',
    tags: ['simulation'],
    component: lazy(() => import('../games/perfect-mine')),
  },
  {
    id: 'restaurant-rush',
    title: 'Restaurant Rush',
    description:
      'Run a restaurant — garden to kitchen to cashier. Wash, chop, bake, blend, and serve customers.',
    thumbnail: '/thumbnails/restaurant-rush.png',
    tags: ['simulation', 'arcade'],
    component: lazy(() => import('../games/restaurant-rush')),
  },
  {
    id: 'tankwars',
    title: 'Tankwars',
    description: 'Tank battle arena.',
    thumbnail: '/thumbnails/tankwars.png',
    tags: ['arcade', 'action'],
    component: lazy(() => import('../games/tankwars')),
  },
  {
    id: 'the-circle-of-life',
    title: 'The Circle of Life',
    description: 'Life cycle simulation game.',
    thumbnail: '/thumbnails/the-circle-of-life.png',
    tags: ['simulation'],
    component: lazy(() => import('../games/the-circle-of-life')),
  },
  {
    id: 'the-button',
    title: 'The Button',
    description: "Don't press the button. Can you resist?",
    thumbnail: '/thumbnails/the-button.png',
    tags: ['silly'],
    component: lazy(() => import('../games/the-button')),
  },
  {
    id: 'the-crappy-game',
    title: 'The Crappy Game',
    description: "It's crappy. You were warned.",
    thumbnail: '/thumbnails/the-crappy-game.png',
    tags: ['silly'],
    component: lazy(() => import('../games/the-crappy-game')),
  },
  {
    id: 'three-snakes',
    title: 'Three Snakes',
    description: 'Three snakes, one arena.',
    thumbnail: '/thumbnails/three-snakes.png',
    tags: ['classic'],
    component: lazy(() => import('../games/three-snakes')),
  },
  {
    id: 'tower-defence',
    title: 'Ragdoll Arena',
    description:
      'Fight ragdoll enemies in 2D — beat levels, earn coins, buy weapons from bat to grenade.',
    thumbnail: '/thumbnails/tower-defence.png',
    tags: ['action', '2d'],
    component: lazy(() => import('../games/tower-defence')),
  },
  {
    id: 'writing-app',
    title: 'Writing App',
    description: "Bo's story writing tool with prompts and save.",
    thumbnail: '/thumbnails/writing-app.png',
    tags: ['creative'],
    component: lazy(() => import('../games/writing-app')),
  },
  {
    id: 'very-long-game',
    title: 'Game That Is A Verryyyyy... Long Game',
    description:
      'A very long sidescroller — portals, springs, push cubes onto buttons to open doors, reach the end.',
    thumbnail: '/thumbnails/very-long-game.png',
    tags: ['platformer', 'puzzle', '2d'],
    component: lazy(() => import('../games/very-long-game')),
  },
]

export function getGameById(id: string): GameConfig | undefined {
  return GAMES.find((game) => game.id === id)
}
